### PR TITLE
Fix logging

### LINKED ISSUE #9: We don't log when creating a topic fails
If you try and create a topic with a configuration that will fail (e.g. higher replication factor than number of available brokers) the exit code will be 1 but there are no logs to explain why.

```
Running kafka-configurator 0.2.0
Topic topic3 not found: creating.
```

The above is the log output for when creating a topic fails.

### PR DESCRIPTION
**Pull request by lacarvalho91**
Closes #9.

Lifts `Try` into the [WriterT](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/WriterT.scala) datatype from Cats to accumulate `INFO` logs and push the logging effect to the main.

### CODE REVIEW

**Comment by oliverlockwood** [comment]
@lacarvalho91 I've not dug too deeply into this; but the examples at http://eed3si9n.com/herding-cats/Writer.html seem to suggest using the `Writer` type alias rather than `WriterT` directly.  I notice we're doing the latter.  Maybe one to talk through?

**Comment by oliverlockwood** [comment]
@lacarvalho91 general feedback:  Although this isn't a large PR, I've been finding it a little hard to review as it mixes refactoring (moving things about between classes, in this case) with the underlying change to how we log, which touches a lot of code.  If there's any chance for things like this to be separated in future, that would aid the reviewer.  Cheers.

File: src/main/scala/com/sky/kafka/configurator/Main.scala [hunk 1]
```diff
@@ -28,24 +27,30 @@ object Main extends LazyLogging {
...
-      _ <- topics.map(configurator.configure).sequenceU
-    } yield ()
-    stopApp(configurator)
-    result
+    run(args) match {
+      case Success((logs, _)) =>
+        logs.foreach(log => logger.info(log))
+        System.exit(0)
+      case Failure(t) =>
+        logger.error(s"Failed to configure topics", t)
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: I've not run this myself, but here's my concern:  If we partially succeed in configuring a few topics, then in the old system we'd get all those logs out first, and then get a failure message when something went wrong.

It *looks* to me like in that case, we'd now only get the failure message, and never know which parts had succeeded prior to the failure.

Am I wrong?

Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: I believe you're correct, looking into it.

File: src/main/scala/com/sky/kafka/configurator/TopicConfigurationParser.scala [hunk 2]
```diff
@@ -2,14 +2,42 @@ package com.sky.kafka.configurator
...
-  def apply(topicConfigReader: JReader): Try[List[Topic]] =
+  def apply(topicConfigReader: JReader): Either[circe.Error, List[Topic]] =
     for {
-      ymlAsJson <- parse(topicConfigReader).toTry
-      topicConfigs <- ymlAsJson.as[List[Topic]].toTry
+      ymlAsJson <- parse(topicConfigReader)
+      topicConfigs <- ymlAsJson.as[List[Topic]]
     } yield topicConfigs
+
+  private case class TopicConfig(partitions: Int, replication: Int, config: Map[String, String])
```
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/TopicConfigurationParser.scala]: this and the decoders below were just moved over as is from the configurator package object

File: src/main/scala/com/sky/kafka/configurator/error/package.scala [hunk 3]
```diff
@@ -0,0 +1,11 @@
+package com.sky.kafka.configurator
+
+package object error {
+
+  case object InvalidArgsException extends Exception
```
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/error/package.scala]: these were just moved over from configurator package object

File: src/main/scala/com/sky/kafka/configurator/Main.scala [hunk 4]
```diff
@@ -28,23 +28,38 @@ object Main extends LazyLogging {
...
+  def run(args: Array[String]): Try[Unit] =
+    parse(args).flatMap { conf =>
+      val configurator = TopicConfigurator.reader(conf)
+      val result = configureTopicsFromFile(conf.file, configurator)
+
+      stopApp(configurator)
+      result
+    }
+
+  private def configureTopicsFromFile(topicConfigYml: File, configurator: TopicConfigurator): Try[Unit] =
```
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: thought it would enhance readability if we extracted running the app logic from the config parsing/app bootstrapping

File: src/main/scala/com/sky/kafka/configurator/Main.scala [hunk 5]
```diff
@@ -28,23 +28,38 @@ object Main extends LazyLogging {
...
+    for {
+      topics <- TopicConfigurationParser(new FileReader(topicConfigYml)).toTry
+      _ <- topics.traverseU { topic =>
+        configurator.configure(topic).run.map {
```
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: log result for each topic individually

**Comment by lacarvalho91** [comment]
Some manual validation would be good for this one

File: src/main/scala/com/sky/kafka/configurator/Main.scala [hunk 6]
```diff
@@ -28,23 +28,38 @@ object Main extends LazyLogging {
       .text("Session and connection timeout for Zookeeper")
   }
 
-  def main(args: Array[String]): Unit = run(args) match {
-    case Success(_) =>
-      System.exit(0)
-    case Failure(_) =>
-      System.exit(1)
+  def main(args: Array[String]): Unit = {
+    logger.info(s"Running ${BuildInfo.name} ${BuildInfo.version}")
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: It's an unrelated change, but do we want to log our arguments here?

File: src/main/scala/com/sky/kafka/configurator/Main.scala [hunk 7]
```diff
@@ -28,23 +28,38 @@ object Main extends LazyLogging {
...
+  private def configureTopicsFromFile(topicConfigYml: File, configurator: TopicConfigurator): Try[Unit] =
+    for {
+      topics <- TopicConfigurationParser(new FileReader(topicConfigYml)).toTry
+      _ <- topics.traverseU { topic =>
+        configurator.configure(topic).run.map {
+          case (logs, _) =>
+            logs.foreach(log => logger.info(log))
+        }.recover {
+          case NonFatal(throwable) =>
+            logger.error(s"Failed to configure ${topic.name}", throwable)
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: Doesn't this `recover` branch mean we'll never exit with a failing return code?

File: src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala [hunk 8]
```diff
@@ -1,53 +1,58 @@
...
+          .withLog(s"Topic ${topic.name} not found: creating.")
+      case Failure(NonFatal(t)) =>
+        Failure(t).asWriter
+    }
+
+  private def updateTopic(oldTopic: Topic, newTopic: Topic): Logger[Unit] = {
+
+    def ifDifferent[T](oldValue: T, newValue: T)
+                      (updateOperation: (Topic, Topic) => Logger[Unit])
+                      (messageIfSame: String): Logger[Unit] =
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala]: like it

File: src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala [hunk 9]
```diff
@@ -1,53 +1,58 @@
...
-      Failure(ReplicationChangeFound)
-    else
-      Success(())
+  private def failReplicationChange(oldTopic: Topic, newTopic: Topic): Logger[Unit] =
+    Failure(ReplicationChangeFound).asWriter
 
+  private def updatePartitions(oldTopic: Topic, newTopic: Topic): Logger[Unit] =
+    topicWriter
+      .updatePartitions(newTopic.name, newTopic.partitions)
+      .withLog(s"Topic ${newTopic.name} has different number of partitions: updating.")
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala]: Is the future/present tense of "updating" inappropriate given this log will only show if the operation is successful?  I'd say "updated" would make more sense.  Or you could change the whole message to:
`Updated topic ${newTopic.name} from ${oldTopic.partitions} to ${newTopic.partitions} partitions`

File: src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala [hunk 10]
```diff
@@ -1,53 +1,58 @@
...
-    if (oldTopic.config != newTopic.config) {
-      logger.info(s"Topic ${newTopic.name} has different configuration: updating.")
-      topicWriter.updateConfig(newTopic.name, newTopic.config)
-    } else {
-      Success(())
-    }
+  private def updateConfig(oldTopic: Topic, newTopic: Topic): Logger[Unit] =
+    topicWriter
+      .updateConfig(newTopic.name, newTopic.config)
+      .withLog(s"Topic ${newTopic.name} has different configuration: updating.")
```
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala]: Similarly, how about:
`Updated configuration of topic ${newTopic.name}`

File: src/main/scala/com/sky/kafka/configurator/Main.scala (hunk 7 above)
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: correct...woops

File: src/main/scala/com/sky/kafka/configurator/Main.scala (hunk 6 above)
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: sure, why not. More info the better I guess

File: src/main/scala/com/sky/kafka/configurator/Main.scala (hunk 7 above)
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: didn't spot that in my testing, just scrolled up and that was indeed happening. Good spot 😄

File: src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala (hunk 8 above)
Comment (lacarvalho91) [inline src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala]: had some help! @matthedude

File: src/main/scala/com/sky/kafka/configurator/Main.scala (hunk 7 above)
Comment (oliverlockwood) [inline src/main/scala/com/sky/kafka/configurator/Main.scala]: 😎
